export default {
  entryPagePath: "pages/authorize/index",
  pages: [
    "pages/member/member",
    "pages/user/index",
    "pages/activity/index",
    "pages/h5/index",
    "pages/update/index",
    "pages/register/index",
    "pages/registerSecond/index",
    "pages/test/index",
    "pages/qy/index",
    "pages/friends/index",
    "pages/apply/index",
    "pages/applyCoupon/index",
    "subPages/service/index",
    "subPages/service/introduce/index",
    "subPages/service/list/index",
    "subPages/service/detail/index",
    "subPages/drawLottery/index",
    "subPages/drawLottery/records/index",
    "subPages/rule/index",
    "pages/sign/index",
    "pages/sign/baLogin/index",
    "pages/sign/qrCode/index",
    "pages/qy/home/index",
    "pages/qy/dashboard/index",
    "pages/qy/recordQuery/index",
    "pages/qy/stockQuery/index",
    "pages/qy/stockSingleQuery/index",
    "pages/qy/debugger/index",
    "pages/authorize/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "NARS会员中心",
    navigationBarTextStyle: "white",
    navigationStyle: "custom",
    backgroundColor: "#000000",
    backgroundColorTop: "#000000",
    backgroundColorBottom: "#000000",
  },
  subpackages: [
    {
      root: "subPages/redeem",
      name: "redeem",
      pages: [
        "index",
        "orderList/index",
        "orderDetail/index",
        "confirm/index",
        "confirmAddress/index",
        "success/index",
      ],
    },
    {
      root: "subPages/common",
      name: "common",
      pages: [
        "pointsDetail/index",
        "consumeRecord/index",
        "myQRCode/index",
        "privacy/index",
      ],
    },
    {
      root: "subPages/applyCoupon",
      name: "applyCoupon",
      pages: ["index"],
    },
    {
      root: "subPages/activity",
      name: "activity",
      pages: ["TRENDS/index", "TECHINIQUES/index"],
    },
    // {
    //   root: "subPages/service-appointment",
    //   name: "serviceAppointment",
    //   pages: [
    //     "index",
    //     "success/index",
    //     "appointment/index",
    //     "detail/index",
    //     "list/index",
    //   ],
    // },
    {
      root: "subPages/coupon",
      name: "coupon",
      pages: ["index"],
    },
    {
      root: "subPages/nearby-stores",
      name: "nearby-stores",
      pages: ["index"],
    },
  ],
  tabBar: {
    backgroundColor: "#000000",
    borderStyle: "white",
    color: "#999999",
    selectedColor: "#FFFFFF",
    list: [
      {
        pagePath: "pages/member/member",
        text: "先锋礼遇",
        iconPath: "assets/image/tabbar/home02.jpg",
        selectedIconPath: "assets/image/tabbar/home.jpg",
      },
      {
        pagePath: "subPages/service/index",
        text: "服务预约",
        iconPath: "assets/image/tabbar/service.png",
        selectedIconPath: "assets/image/tabbar/service02.png",
      },
      {
        pagePath: "pages/user/index",
        text: "MY NARS",
        iconPath: "assets/image/tabbar/user02.jpg",
        selectedIconPath: "assets/image/tabbar/user.jpg",
      },
    ],
  },
  requiredPrivateInfos: ["getLocation", "chooseAddress"],
  permission: {
    "scope.userLocation": {
      desc: "你的位置信息将用于定位附近的门店信息",
    },
  },
  __usePrivacyCheck__: true,
};
